/*
 * Async Output Service API
 *
 * An API for real-time matching of asynchronous output generation with client consumption.  The service acts as a matching intermediary between applications generating outputs  asynchronously and clients waiting to receive specific outputs in real-time.  **Core Concept**: Stream-based matching using streamID to connect senders with receivers.  **Phase 1**: Real-time in-memory matching with long polling **Phase 2**: Persistent storage with replay capability
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package genapi

type SendAndStoreRequest struct {

	// Unique identifier for the output
	OutputUuid string `json:"outputUuid"`

	// Unique identifier for the output stream
	StreamId string `json:"streamId"`

	// The output data to store as JSON object
	Output map[string]interface{} `json:"output"`

	// Time-to-live for the stored output (e.g., \"1h\", \"24h\", \"7d\")
	Ttl string `json:"ttl,omitempty" validate:"regexp=^[0-9]+[smhd]$"`
}
