/*
 * Distributed Durable Timer Service API
 *
 * A distributed, durable timer service that can schedule and execute HTTP webhook callbacks  at specified times with high reliability and scalability.  ## Features - Create one-time timers with custom payloads - Durable persistence across service restarts - At-least-once delivery semantics - Configurable retry policies and timeouts - Timer modification and cancellation - Callback response can update timer schedule - Namespace-based timer uniqueness
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package genapi

import (
	"time"
)

type Error struct {

	// Error code
	Error string `json:"error"`

	// Human-readable error message
	Message string `json:"message"`

	// Additional error details
	Details map[string]interface{} `json:"details,omitempty"`

	// When the error occurred
	Timestamp time.Time `json:"timestamp,omitempty"`
}
