/*
 * Distributed Durable Timer Service API
 *
 * A distributed, durable timer service that can schedule and execute HTTP webhook callbacks  at specified times with high reliability and scalability.  ## Features - Create one-time timers with custom payloads - Durable persistence across service restarts - At-least-once delivery semantics - Configurable retry policies and timeouts - Timer modification and cancellation - Callback response can update timer schedule - Namespace-based timer uniqueness
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package genapi

import (
	"time"
)

type CallbackResponse struct {

	// Whether the callback is successful. If false, the timer will be retried (same as not returning 200).
	Ok bool `json:"ok"`

	// ISO 8601 timestamp when the timer should execute next time. Only valid when ok is false.
	NextExecuteAt time.Time `json:"nextExecuteAt,omitempty"`
}
